import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faUser,
  faLock,
  faEnvelope,
  faIdCard,
  faCheckCircle,
  faCalendarCheck,
  faUsers,
  faEdit,
  faTrash,
  faPlus,
  faBars,
  faTimes,
  faQrcode,
  faEye,
  faEyeSlash,
  faSignInAlt,
  faUserPlus,
  faClipboardCheck,
  faClock,
  faSearch,
  faFilter,
  faDownload,
  faRefresh,
} from '@fortawesome/free-solid-svg-icons';

// Add icons to FontAwesome library
library.add(
  faUser,
  faLock,
  faEnvelope,
  faIdCard,
  faCheckCircle,
  faCalendarCheck,
  faUsers,
  faEdit,
  faTrash,
  faPlus,
  faBars,
  faTimes,
  faQrcode,
  faEye,
  faEyeSlash,
  faSignInAlt,
  faUserPlus,
  faClipboardCheck,
  faClock,
  faSearch,
  faFilter,
  faDownload,
  faRefresh,
);