// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzcpnikdoxsubccqvoxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Y3BuaWtkb3hzdWJjY3F2b3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzE4MTIsImV4cCI6MjA3MTIwNzgxMn0.eUiYV4x_cWvD1EuLAU5xIz_NDzYsb9AFq4riEICGdNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});